default:
	g++ -std=c++11 -g *.cpp -o ./main.o -lzstd -pthread

debug:
	g++ -std=c++11 -g *.cpp -o ./main.o -lzstd -pthread -D DEBUG_OUTPUT

time:
	g++ -std=c++11 -g *.cpp -o ./main.o -lzstd -pthread -D TIME_OUTPUT
