default:
	g++ -std=c++11 -g *.cpp -o ./main.o -lzstd -O3 -pthread

debug:
	g++ -std=c++11 -g *.cpp -o ./main.o -lzstd -O3 -pthread -D DEBUG_OUTPUT

time:
	g++ -std=c++11 -g *.cpp -o ./main.o -lzstd -O3 -pthread -D TIME_OUTPUT
